from tests.test_new import TestNew
from tests.test_film import TestFilms
from tests.test_search import TestSearch
from tests.test_series import TestSeries
from tests.test_HDrezka import TestHDrezka
from tests.test_cartoon import TestCartoons
from tests.test_announce import TestAnnounce
from tests.test_meta_data import TestMetaData
from tests.test_animation import TestAnimations
from tests.test_collections import TestCollections
