name: Tests

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", "3.12" ]
        exclude:
          - { os: macos-latest, python-version: "3.7" }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: ${{ matrix.python-version }} on python ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pylint

      - name: Analyse code with Pylint
        run: |
          pylint HDrezka --fail-under=9

      - name: Run tests
        run: |
          python3 -m tests