name: Tests

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  run-tests:
    continue-on-error: true
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", "3.12" ]
        exclude:
          - { os: macos-latest, python-version: "3.7" }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python environment
        uses: actions/cache@v4
        with:
          path: venv/
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-venv-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ matrix.python-version }}-venv-

      - name: Install dependencies
        if: steps.cached-dependencies.outputs.cache-hit != 'true'
        shell: bash
        run: |
          python -m venv venv
          . venv/$(if [[ "$RUNNER_OS" == "Windows" ]]; then echo "Scripts"; else echo "bin"; fi)/activate
          
          python -m pip install --upgrade pip
          python -m pip install --upgrade --upgrade-strategy eager -r requirements.txt -r requirements-dev.txt
          python -m pip install pylint

      - name: Analyse code with Pylint
        shell: bash
        run: |
          . venv/$(if [[ "$RUNNER_OS" == "Windows" ]]; then echo "Scripts"; else echo "bin"; fi)/activate
          python -m pylint HDrezka --fail-under=9

      - name: Run tests
        shell: bash
        run: |
          . venv/$(if [[ "$RUNNER_OS" == "Windows" ]]; then echo "Scripts"; else echo "bin"; fi)/activate
          python -m tests
