name: Tests

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", "3.12" ]
        exclude:
          - { os: macos-latest, python-version: "3.7" }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python environment
        id: cached-dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}

      - name: Install dependencies
        if: steps.cached-dependencies.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r requirements.txt -r requirements-dev.txt
          pip install pylint

      - name: Analyse code with Pylint
        run: |
          python3 -m pylint HDrezka --fail-under=9

      - name: Run tests
        run: |
          python3 -m tests
